baseURL = 'https://s0ph0s.dog/'
languageCode = 'en-us'
title = 's0ph0s'
theme = 'backslash'
copyright = "© 2021 s0ph0s"

[author]
name = "s0ph0s"
email = "s0ph0s@protonmail.com"
uri = "https://s0ph0s.dog/"

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    pre = "home"
    weight = 1
  [[menu.main]]
    name = "About"
    url = "/about/"
    pre = "silhouette-v2"
    weight = 2
  [[menu.main]]
    name = "Blog"
    url = "/blog/"
    pre = "blog"
    weight = 3
  [[menu.main]]
    name = "Gallery"
    url = "/gallery/"
    pre = "photo-landscape-v2"
    weight = 4
  [[menu.main]]
    name = "Tags"
    url = "/tags/"
    pre = "tag"
    weight = 5

  [[menu.contact]]
    name = "Telegram"
    url = "https://t.me/s0ph0s"
    pre = "telegram"
    weight = 1
  [[menu.contact]]
    name = "GitHub"
    url = "https://github.com/s0ph0s-2"
    pre = "octocat"
    weight = 2
  [[menu.contact]]
    name = "Email"
    url = "mailto:awoo@s0ph0s.dog"
    pre = "email"
    weight = 3
