baseURL = 'https://s0ph0s.dog/'
languageCode = 'en-us'
title = 's0ph0s'
theme = 'backslash'

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2
  [[menu.main]]
    name = "Blog"
    url = "/blog/"
    weight = 3
  [[menu.main]]
    name = "Gallery"
    url = "/gallery/"
    weight = 4
  [[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 5
